### ISSUE TITLE
are all the functions used?

### ISSUE THREAD

**Issue by fawazsammani** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#10]
Hi. Thanks for that Tutorial.
I would like to ask. I have realized some unused functions through the code. In utils file, the function load_embeddings (different from load_pretrained_embeddigns in model.py) is not used.  So are they necessary to add them?

**Comment by fawazsammani** [comment]
Sorry, looks like I misread some other issues. I know understand that you have included it in case any loading of a pretrained embeddings is desired.

**Comment by sgrvinod** [comment]
I'm using [`AdaptiveAvgPool2d()`](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/b0191b381ab5ee6970921c771dba57f16bc09a46/models.py#L24) to reshape the final image, whatever its size is, to (14, 14). This means you can supply images of variable sizes to the encoder, and the output would always be the same size and you wouldn't need to worry about a size mismatch downstream.

**Comment by sgrvinod** [comment]
That is, the regular Resnet101, without the adaptive average pooling, would reduce the original image size by a factor of 32 (from 224, in ImageNet, to 7). With the adaptive pooling, it reduces the original image size to a fixed dimension and not by a fixed factor.

**Comment by fawazsammani** [comment]
![1](https://user-images.githubusercontent.com/30661597/44133025-30b29072-a012-11e8-9e15-bdc236707b88.PNG)
Because if you refer to this image, then after removing the last 2 layers according to your code, then the output size is (2048,7,7). Can the average pooling in that case increase the image size? In that case it's unpooling, or transposed convolution....etc
Can you please clarify on this point? Thanks in advance

**Comment by sgrvinod** [comment]
Yes, if the image before the adaptive pooling is smaller than (14, 14), it will make the image larger. It just stretches it.

Here's an example -

![image](https://user-images.githubusercontent.com/10481431/44133385-2e131baa-a07d-11e8-81d8-a98b8c5a6d01.png)

Adaptive pooling is just a practice I employ with my CNNs to deal with the possibility of images of different sizes. Without adaptive pooling, the final size might not always be (7, 7), depending on the original size, and this will throw an error since the encoding will be of a different size than expected.

My choice of `14` is somewhat arbitrary - you can experiment with different encoding sizes, or simply without adaptive pooling. But in this case you will need to take care that the input image will always be the same size, even during inference.

**Comment by fawazsammani** [comment]
Thanks! Really appreciate it
