### ISSUE TITLE
Regarding the Attention Addition

### ISSUE THREAD

**Issue by fawazsammani** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#28]
Hi @sgrvinod 
I would like to ask regarding the addition of the attention in `att1 + att2.unsqueeze(1)`
`att1` is of shape `(N, pixels, att_dim)`
`att2` after `unsqueeze` is of shape `(N,1,att_dim)`

When you are adding `att1` and `att2`, then `att2` is being expanded automatically to be of the same shape as `att1`. Therefore, you are adding the same thing for every row of `att1` (i.e. all pixels of `att1` get added to the same values). Is that how it should be? Or must we multiply `att2` with a `ones` matric to reshape the attention size, as in the following code:
```
        ones_mx = torch.ones(batch_size], 1, att_dim).to(device) # (batch_size, 1, att_dim)
        hidden_mul = torch.bmm(att2.unsqueeze(2), ones_mx) # (N,49,1 bmm N,1,49) --> (N,49,49) (batch_size,att_dim, att_dim)
        addition_out = F.relu(att1 + hidden_mul)   # (batch_size,49,49)
```
Or does it not matter?

Thanks

**Comment by sgrvinod** [comment]
Yes, that's right. we're adding the same thing to each pixel because each pixel (in `att1`) will be evaluated with respect to the same thing, i.e. the hidden state of the decoder (`att2`). 

I think the equivalent of the first two lines of code in your question is:
```
hidden_mul = att2.unsqueeze(2).expand(N, att_dim, att_dim) # (N, att_dim) -> (N, att_dim, 1) -> (N, att_dim, att_dim)
```
In this case, `att2` is getting broadcasted along the 3rd dimension. But we'd actually need to broadcast it along the 2nd dimension since they need to be the same for each pixel, and the pixels are the 2nd dimension of `att1`.

**Comment by andreydung** [comment]
Would `add` be a suitable operator here? Since we are checking the compatibility between `att1` and `att2`, should we use concat, or diff instead?
