### ISSUE TITLE
Sampling method not following the paper?

### ISSUE THREAD

**Issue by PabloRR100** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#33]
Hi,

In section 4.3 authors mention that they randomly choose a caption length and then retrieve a minibatch of that length using a previously built dictionary.

Why not using this approach instead of having to pad the captions and order by caption length and then sampling by length in the loop?

**Comment by sgrvinod** [comment]
> As our implementation requires time proportional to the length of the longest sentence per update, we found training on a random group of captions to be computationally wasteful. To mitigate this problem, in preprocessing we build a dictionary mapping the length of a sentence to the corresponding subset of captions. Then, during training we randomly sample a length and retrieve a mini-batch of size 64 of that length. We found that this greatly improved convergence speed with no noticeable diminishment in performance. On our largest dataset (MS COCO), our soft attention model took less than 3 days to train on an NVIDIA Titan Black GPU.

I assume they did this only from the standpoint of the time taken for each batch. As @kmario23 points out, there is no extra computation in our code since we're handling everything dynamically. But there _is_ a slight time inefficiency in that the loop still runs to the maximum sentence length just for the sake of one or two long sentences in that batch. 

I guess the downside with the same-length batch is that the order of training is not truly random in this case, so one might expect a slight decrease in performance, and hence they specifically report that this decrease wasn't noticeable. 

I didn't feel the need to do this because training is pretty fast anyway. I felt it is nicer (and more generally applicable) to randomly sample sentences in each batch, and also to demonstrate that PyTorch can be used flexibly and about the utility of packed sequences.

**Comment by PabloRR100** [comment]
I totally understood.
Thank you very much and great work : )
