### ISSUE TITLE
why are you using pack padded seq if you've already removed the pads in inputs?

### ISSUE THREAD

**Issue by homelifes** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#40]
Hi. Thanks for your work on "Show Attend and Tell".
In training file, you have used `scores, _ = pack_padded_sequence(scores, decode_lengths, batch_first=True)` and said that this is to remove the timesteps that we didn't decode at. 
However, when feeding in the inputs to the LSTM, you have used: `batch_size_t = sum([l > t for l in decode_lengths])`, which means originally,  you are only taking the effective batch size and not any pads. So i assume there is no need to use `pack_padded_sequence` in this case?

**Comment by sgrvinod** [comment]
Hi, as you said, we didn't decode at the pads because we used only processed the effective batch size.  But there are still pads in the final tensor that we're passing around. 

See [this line](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/5d0faf5ea4d0dbfdfe1af11d22462fccee49fcc2/models.py#L211). We're storing the results of the non-pad timesteps back into a padded tensor, which is returned as `scores`.
