### ISSUE TITLE
How to recover training at a check point

### ISSUE THREAD

**Issue by luulinh90s** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#49]
As you wrote in README, it is possible to use checkpoint flag to start training at a certain point instead of training from scratches, but in code, there is no option for that. 

I am supposing that you have not implemented this feature yet, right? So if it is true, please modify your README page, since that really makes us confused.

**Comment by sgrvinod** [comment]
Hi @luulinh90s, everything in the tutorial has been implemented unless I've mentioned otherwise. The `checkpoint` variable is [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/903ebcc8b64d35592b65c00d56e109d68c3f709b/train.py#L38). The code that loads the checkpoint using the path provided in the `checkpoint` variable is [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/903ebcc8b64d35592b65c00d56e109d68c3f709b/train.py#L67-L79).
