### ISSUE TITLE
Low volatile GPU-Util but high GPU Memory Usage

### ISSUE THREAD

**Issue by ruizhao1997** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#53]
When I run the code, I find that the volatile GPU-Util is only 2% or 1% while the Memory-Usage is 8 GB. Do you guys know how to achieve a more efficient volatile GPU-Util? Thanks a lot!

**Comment by sgrvinod** [comment]
Hi @ruizhao1997, I suspect this is because the dataloading is slow and therefore can't serve data to the GPU as fast as the GPU can process it. Honestly, I think my choice of using the HDF5 files for the images wasn't the best. I was kind of new to computer vision at that time, so I thought it was a good idea. Moreover, we [can't use more than one CPU process with `h5py`](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/15#issuecomment-441081706).

I think it may be faster to just store lists of the image paths, their captions, and their caption lengths, and then read the image directly from disk in the Dataset object, [like I did in the Object Detection tutorial](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection/blob/0d38943b68e2664039e4c22b2838d634b656a927/datasets.py#L37), with more CPU workers. 

There are other factors, of course, like whether you're using an SSD, etc. I distinctly remember that training was much slower when I had the data on my mechanical HDD.

**Comment by ruizhao1997** [comment]
Thanks for your quick response. I think this really help me a lot, and I will try to deal with data in the way you suggested. 

Actually, I'm a beginner in CV, and this project help me a lot to learn the attention, image caption and  pytorch. Thanks for sharing this great project!

**Comment by sgrvinod** [comment]
Glad you found it useful and happy to help! Let me know if my suggestion leads to any improvement, and I will change the code accordingly.

**Comment by ruizhao1997** [comment]
OK!

**Comment by ruizhao1997** [comment]
I changed to load image directly from disk, but the phenomena is almost the same. 

After a series of comparisons, I found that this may be a mistake caused by the task manager. When I run the code, the 'nvidia-smi' show me the volatile GPU-Util is over 90%, while the task manager tell me it's only 2%. 

This is what the vidia-smi shows below:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 385.54                 Driver Version: 385.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|     Memory-Usage | GPU-Util  Compute M. |
|=====================+=============+===========|
|   0  TITAN X (Pascal)   WDDM  | 00000000:01:00.0  On |                  N/A |
| 50%   84C    P2 195W / 250W |   6378MiB / 12288MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
```

This is what the task manager shows below:
```
	NVIDIA TITAN X (Pascal)
	Utilisation	2%
	Dedicated GPU memory	6.1/12.0 GB
	Shared GPU memory	0.3/16.0 GB
	GPU Memory	6.4/28.0 GB
```

I guess that the low Shared GPU memory leads to the low Utilisation, while the Dedicated GPU memory is actually high.

Task manager misled me. The truth is that the code runs well, and the volatile GPU-Util is not low.

**Comment by kmario23** [comment]
@sgrvinod  @ruizhao1997  Just wanted to add that the way we load the images as done in [datasets.py#L25](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/master/datasets.py#L25) is actually the fastest that you can get. It should be blazing fast even if you have petabytes of data (see more information about this at: [Fast and efficient way of serializing and retrieving a large number of numpy arrays from HDF5 file](https://stackoverflow.com/questions/53026032/fast-and-efficient-way-of-serializing-and-retrieving-a-large-number-of-numpy-arr) ). In my experience, there's no other optimized way than this.

Having said that, it is still not a good approach to preprocess the images to HDF5 files, particularly when you have a mountain of data. It'd then prolly be best to go with [PyTorch DataLoader](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html)

**Comment by kmario23** [comment]
@sgrvinod I have implemented the version where we load images directly from the disk (and apply the necessary preprocessing on the fly) instead of first preprocessing and serializing them to `.hdf5` files. Is it desirable to have this new version in the repo? If yes, I can send a PR. Please let me know!

**Comment by ruizhao1997** [comment]
@kmario23 Good job! 

But I want to know that, will there be a  a more efficient volatile GPU-Util when you load images directly from the disk?

**Comment by kmario23** [comment]
Hi @ruizhao1997 , thanks! At my end, with a batch size of 128, the `GPU-Util` fluctuates between 71-100%. As for the CPU utilization, I cannot tell exactly since I use 24 core machine and the usage varies widely. However, I found out that reading images directly from disk improves training time up to 30 mins per epoch. And this saves quite lot of time (30 * 40) = 20 hrs :)

**Comment by sgrvinod** [comment]
@kmario23 I agree wholeheartedly. Even if it didn't improve the speed or utilization significantly, I think using HDF5 files is just too clunky and awkward. Like you said, when there's a lot of data, we'd rather just read images from an efficient image format (like JPEG or whatever) than from this huge array that's taking a mountain of space on our disk. Not to mention the time spent in creating the HDF5 file and the multithreading limitations. 

About the PR, sure, thanks. I won't be able to take a look at it immediately though since I'm traveling.

**Comment by ruizhao1997** [comment]
@kmario23 I'm looking forward to speeding up! Waiting for your PR. Thanks a lot.

**Comment by xinyuwang1126** [comment]
@kmario23 Hi Mario is your version integrated now? (I didn't see that in commit history). If not, may I have a look at it? I am also having issue with dataloading. Thank you!

**Comment by kmario23** [comment]
Hey @xinyuwang1126 it's not integrated in this codebase yet. However, I have implemented a modified dataloader (for directly reading images from the disk) using which I'm training models on the GPU cluster machines here.

**Comment by sonniki** [comment]
Hey @kmario23 it's been a couple of years but I was wondering if you could share the code for the dataloader that reads the images directly from the disk? It would help my project immensely!
